CREATE TABLE person (
    id          int GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255),
    city        varchar(255),
    StreetName  varchar(255),
    old         Integer,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

