CREATE TABLE person (
    id          int GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255),
    cpf         varchar(255),
    city        varchar(255),
    StreetName  varchar(255),
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

